### ISSUE TITLE
Angles inconsistency

### ISSUE THREAD

**Issue by kobalino** [spacetelescope/sphere#57]
I need to determine the surface angle of three points on a sphere, but the results I get with your library seems inconsistent or inaccurate.

Here is the gist : https://gist.github.com/0af604cbdc572b285f18.git

Thank you for your help

**Comment by bernie-simon** [comment]
Thank you for providing a testcase, it make solving the problem much easier. 

There are two problems with the test case you provide. 

First, it looks like the three points you are using to define the triangle are in the form (ra, dec, 0) where ra and dec are in degrees. Then you do two operations on the three using methods from the SphericalPolygon package. The first is that you call normalize_vector on the three points. This is not valid because the points are not three-vectors. The normalize_vector method assumes its input is a three vector which is to be normalized by dividing each component of the vecor by the magnitude of the vector. This is not true if the vector contains (ra, dec, 0) as it seems to,

Second, you create a new SphericalPolygon object and are calling deg2rad on the arguments you are passing to it. This is not a problem, except that SphericalPolygon has a keyword argument, degrees, and its default value is true. The result is that the degrees to radians conversion is called twice on your input and this leads to an erroneous result. 

There's another issue: it looks like you are using an older version of the code. I say this because the points method of SphericalPolygon now returns a generator instead of an array, so the current version of the code will not run without modification. But this does not affect the main result.

I think if you modify the code that this test case is based on to fix the two problems mentioned above, it will work correctly. If you find another problem, please let us know and we will address it.
