### ISSUE TITLE
SphericalPolygon.area incorrect?

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/sphere#64]
The area doesn't seem right in the following example:

```python
>>> from spherical_geometry.polygon import SphericalPolygon
>>> s = SphericalPolygon.from_radec([10, 20, 20, 10, 10], [10, 10, 20, 20, 10], degrees=True)
>>> print(s.area())
12.5369248525
```

If it's in radians, it's too large, and if it's in degrees, it's too small.

**Comment by mdboom** [comment]
Since the polygon is in the wrong direction and you aren't providing an inside point, the area is the entire sphere (4π) *minus* a small rectangle.  Reverse the points or provide an inside point.  This is one of the special gotchas of spherical geometry and is explained here:

https://spacetelescope.github.io/sphere/spherical_geometry/user.html#where-is-the-inside
